# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- refs/tags/*-internal

pr: none

pool:
  vmImage: 'macOS-10.13'

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'google-play-service-account-key.json'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'google-play-upload-key.jks'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'signing.gradle'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Agent.TempDirectory)'
    contents: '**' 
    targetFolder: '$(Build.SourcesDirectory)/Secure'

- script: echo -e 'ext{\ninstantVersionCode=$(Build.BuildId)*2-1\ninstalledVersionCode=$(Build.BuildId)*2\nversionNamePostfix=$(Build.BuildId)\ngooglePlayTrack=\"internal\"\n}' > Secure/version.gradle
  displayName: Make version.gradle

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'publishInstalledReleaseBundle'

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'bundleInstantRelease'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'InternalInstantBundle'
    targetPath: 'app/build/outputs/bundle/instantRelease'
