# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- refs/tags/*-internal

pool:
  vmImage: 'macOS-10.13'

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'TestSecureFile.txt'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$env:DOWNLOADSECUREFILE_SECUREFILEPATH'
    contents: '**' 
    targetFolder: '$(Build.ArtifactStagingDirectory)\Secure'
    
- script: tree
  displayName: Show Directory  
